// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";

// 1. Import ThemeProvider
import { ThemeProvider } from "@/components/theme-provider";
import { Providers } from '@/lib/providers';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // 2. Tambahkan suppressHydrationWarning pada <html>
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}